server.port: 8080
logging.level.org.zalando.logbook: TRACE

spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:file:./db/filmorate
    # url=jdbc:h2:mem:testdb:
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect