-- DROP TABLE IF EXISTS rate_review;
-- DROP TABLE IF EXISTS reviews;
-- DROP TABLE IF EXISTS friendship;
-- DROP TABLE IF EXISTS film_genre;
-- DROP TABLE IF EXISTS likes;
-- DROP TABLE IF EXISTS genres;
-- DROP TABLE IF EXISTS films;
-- DROP TABLE IF EXISTS mpa;
-- DROP TABLE IF EXISTS users;



CREATE TABLE IF NOT EXISTS genres
(
    id      SMALLINT GENERATED BY DEFAULT AS IDENTITY,
    name    CHARACTER VARYING(64)  NOT NULL UNIQUE,
    CONSTRAINT pk_genres PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS mpa
(
    id      SMALLINT  GENERATED BY DEFAULT AS IDENTITY,
    name    CHARACTER VARYING(5)   NOT NULL UNIQUE,
    CONSTRAINT pk_mpa PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS films (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(128) NOT NULL,
    description VARCHAR(200),
    mpa_id SMALLINT NOT NULL,
    release_date DATE,
    duration INTEGER NOT NULL,
    CONSTRAINT pk_films PRIMARY KEY (id),
    CONSTRAINT chk_films_duration CHECK (duration > 0),
    FOREIGN KEY (mpa_id) REFERENCES mpa(id)
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    login VARCHAR(32) NOT NULL,
    username VARCHAR(128) NOT NULL,
    email VARCHAR(255) NOT NULL,
    birthday DATE,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uq_users_login UNIQUE (login),
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT chk_login_length CHECK (LENGTH(login) BETWEEN 3 AND 32)
);

CREATE TABLE IF NOT EXISTS film_genre (
    film_id BIGINT NOT NULL,
    genre_id SMALLINT NOT NULL,
    CONSTRAINT pk_film_genre PRIMARY KEY (film_id, genre_id),
    FOREIGN KEY (film_id) REFERENCES films(id) ON DELETE CASCADE,
    FOREIGN KEY (genre_id) REFERENCES genres(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS likes (
    film_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_likes PRIMARY KEY (film_id, user_id),
    FOREIGN KEY (film_id) REFERENCES films(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS friendship (
    user_id BIGINT NOT NULL,
    friend_id BIGINT NOT NULL,
    CONSTRAINT pk_friendship PRIMARY KEY (user_id, friend_id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (friend_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT no_self_friendship CHECK (user_id != friend_id)
);

CREATE TABLE IF NOT EXISTS reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    content VARCHAR(800) NOT NULL,
    is_positive BOOL,
    user_id BIGINT NOT NULL,
    film_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_reviews PRIMARY KEY (id),
    CONSTRAINT unique_user_film UNIQUE (user_id, film_id),
    CONSTRAINT chk_reviews_content CHECK (content <> ''),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (film_id) REFERENCES films(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS rate_review (
    user_id BIGINT NOT NULL,
    review_id BIGINT NOT NULL,
    is_useful BOOL NOT NULL,
    CONSTRAINT unique_user_review UNIQUE (user_id, review_id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (review_id) REFERENCES reviews(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS directors (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR NOT NULL,
     CONSTRAINT pk_directors PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS film_director (
 director_id INT,
 film_id BIGINT,
 CONSTRAINT pk_film_director PRIMARY KEY (director_id, film_id),
 FOREIGN KEY (film_id) REFERENCES films(id) ON DELETE CASCADE,
 FOREIGN KEY (director_id) REFERENCES directors(id) ON DELETE CASCADE
);